[tool.poetry]
name = "app"
version = "0.0.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.11"
psycopg2-binary = "^2.9.9"
plainframework = {git = "https://github.com/dropseed/plain", branch = "main", subdirectory = "plain"}
"plain.models" = {git = "https://github.com/dropseed/plain", branch = "main", subdirectory = "plain-models"}
"plain.auth" = {git = "https://github.com/dropseed/plain", branch = "main", subdirectory = "plain-auth"}
"plain.code" = {git = "https://github.com/dropseed/plain", branch = "main", subdirectory = "plain-code"}
"plain.passwords" = {git = "https://github.com/dropseed/plain", branch = "main", subdirectory = "plain-passwords"}
"plain.pytest" = {git = "https://github.com/dropseed/plain", branch = "main", subdirectory = "plain-pytest"}
"plain.sessions" = {git = "https://github.com/dropseed/plain", branch = "main", subdirectory = "plain-sessions"}
"plain.staff" = {git = "https://github.com/dropseed/plain", branch = "main", subdirectory = "plain-staff"}
"plain.tailwind" = {git = "https://github.com/dropseed/plain", branch = "main", subdirectory = "plain-tailwind"}
"plain.htmx" = {git = "https://github.com/dropseed/plain", branch = "main", subdirectory = "plain-htmx"}
"plain.elements" = {git = "https://github.com/dropseed/plain", branch = "main", subdirectory = "plain-elements"}

[tool.poetry.group.dev.dependencies]
"plain.dev" = {git = "https://github.com/dropseed/plain", branch = "main", subdirectory = "plain-dev"}

[tool.plain.dev.services]
postgres = {cmd = "docker run --name app-postgres --rm -p 54321:5432 -v $(pwd)/.plain/dev/pgdata:/var/lib/postgresql/data -e POSTGRES_PASSWORD=postgres postgres:15 postgres"}

[tool.plain.tailwind]
version = "3.4.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
